#!/bin/bash

# compile twice and rename
pdflatex -synctex=1 ./master.tex
pdflatex -synctex=1 ./master.tex
cp master.pdf free_range_vhdl.pdf
cp master.synctex.gz free_range_vhdl.synctex.gz
rm master.pdf
rm master.synctex.gz
